# Generated by Django 3.0.4 on 2020-06-02 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('NGO_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('type', models.CharField(choices=[('None', 'Choose an option'), ('Profit', 'Profit'), ('Non Profit', 'Non Profit'), ('Charitable Oriented', 'Charitable Oriented'), ('Empowerment Oriented', 'Empowerment Oriented')], default='None', max_length=20)),
                ('description', models.TextField()),
                ('merchant_id', models.CharField(max_length=20)),
                ('merchant_key', models.CharField(max_length=20)),
                ('NGO_website', models.URLField(max_length=100)),
                ('contact_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Enter a 10 digit mobile number', regex='^.{10}$')])),
            ],
        ),
    ]
