# Generated by Django 3.0.4 on 2020-06-02 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(max_length=20)),
                ('merchant_key', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Done'), (2, 'Failed')], default=0)),
                ('NGO_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='status.NGO')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
