# Generated by Django 3.0.4 on 2020-06-02 20:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_string', models.CharField(default='0010', max_length=120)),
                ('driverName', models.CharField(blank=True, max_length=50)),
                ('car_number', models.CharField(max_length=13)),
                ('contact_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Enter a 10 digit mobile number', regex='^.{10}$')])),
                ('NGO_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='status.NGO')),
            ],
        ),
    ]
