# Generated by Django 3.0.4 on 2020-06-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.AlterField(
            model_name='driver',
            name='qr_string',
            field=models.CharField(default='0010', max_length=120, primary_key=True, serialize=False),
        ),
    ]
