# Generated by Django 3.0.4 on 2020-06-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20200603_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='NGO_id',
        ),
    ]
